# Generated by Django 6.0.7 on 2026-08-03 18:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Telefon numarası '5XXXXXXXXX' veya '+905XXXXXXXXX' formatında olmalıdır.", regex='^(\\+?90)?5\\d{9}$')], verbose_name='Telefon'),
        ),
    ]
